variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}"/.sonar"
  GIT_DEPTH: "0"

stages:
  - build

build-check:
  stage: build
  image: gradle:8.4.0-jdk11
  cache:
    key: "${CI_JOB_NAME}"
    path:
      - .sonar/cache
  script: gradle sonarqube
  rules:
    - if: '$CI_BUILD_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'