stages:
  - test
  - integrationTest
  - smokeTest
  - regressTest
  - performanceTest
  - sonarqube-check
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  stage: test
  script:
    - gradle test

integrationTest:
  stage: integrationTest
  script:
    - gradle integTest

smokeTest:
  stage: smokeTest
  script:
    - gradle smokeTest

regressTest:
  stage: regressTest
  script:
    - gradle regressTest

performance_test:
  stage: performanceTest
  script:
    - bzt taurus_config.yaml
  before_script:
    - gradle bootJar
    - docker compose up -d
    - sleep 10
  after_script:
    - docker compose down --volumes
  when: manual

deploy:
  stage: deploy
  script:
    - gradle bootJar
    - echo ${CI_ARTIFACTORY_PASSWORD} | docker login -u autum --password-stdin registry.gitlab.com/skillbox-microservices1/users-service
    - docker build -t registry.gitlab.com/skillbox-microservices1/users-service/users-service:1.0.0-SNAPSHOT .
    - docker push registry.gitlab.com/skillbox-microservices1/users-service/users-service:1.0.0-SNAPSHOT

#build-check:
#  stage: test
##  cache:
##    key: "${CI_JOB_NAME}"
##    path:
##      - .sonar/cache
#  script: gradle sonarqube -Dsonar.qualitygate.wait=true
#  rules:
#    - if: '$CI_BUILD_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'