server:
  port: 19919

spring:
  profiles:
    active: dev
  application:
    name: users-service

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG